---
name: Pre-Commit

# Set default permissions to empty, make zizmor happy
permissions: {}

on:
    # Should it be needed, allow manual triggering
    workflow_dispatch:
    # Run on any push to non-master branch
    push:
        branches-ignore:
            - main

jobs:
    pre-commit:
        name: run pre-commit hooks
        runs-on: ubuntu-latest
        permissions:
            # Required for workflows in private repositories
            contents: read

        steps:
            - name: Checkout Repo
              id: checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Install uv
              id: setup_uv
              uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
              with:
                  enable-cache: true
                  ignore-nothing-to-cache: true

            - name: Set up Python And Pre-Commit
              id: setup_python_pre-commit
              run: |
                  uv python install
                  uv tool install pre-commit

            # TODO: only if early steps succeeded
            - name: Run pre-commit hooks
              id: check_pre_commit
              run: |
                  uv run pre-commit run --all-files
